### ISSUE TITLE
Does this library is live?

### ISSUE THREAD

**Issue by IlyaBaudin** [bugfender/BugfenderSDK-macOS#1]
Hello guys. Thanks a lot for your product.
I use BugfenderSDK on iOS and it works fine.

Can you tell does current BugfenderSDK-macOS repository is live? Does it possible to use Bugfender on macOS or not? I see that library marked as BETA but all provided documentation in repo about iOS, not macOS. 

Thanks a lot

**Comment by jgimenez** [comment]
Hi @IlyaBaudin , yes, this library has not been updated in some time but you can use it. It's lacking some of the features added more recently to the iOS version, but we have customers using it without issues.

Please note if you have a "UIKit for Mac" (Project Catalyst) application, I recommend the iOS library, which will work both on iOS and Mac. Now that it is possible with the introduction of xcframeworks, our plan is to merge this library with the iOS one, so you get the most recent updates as well.

**Comment by IlyaBaudin** [comment]
@jgimenez thanks a lot.

Should I expect a library update or there are no such plans?

**Comment by jgimenez** [comment]
Yes, as explained in my previous comment, we will merge this library with the other one

**Comment by IlyaBaudin** [comment]
I see. Thanks)
